apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: streaming-platform
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - port: 3000
      targetPort: 3000

