apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-service-hpa
  namespace: streaming-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

