apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: streaming-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
      - name: catalog-service
        image: catalog-service:latest
        ports:
          - containerPort: 3002
