apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-service
  namespace: streaming-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-service
  template:
    metadata:
      labels:
        app: streaming-service
    spec:
      containers:
        - name: streaming-service
          image: streaming-service:latest
          ports:
            - containerPort: 3003
