apiVersion: v1
kind: Service
metadata:
  name: streaming-service
  namespace: streaming-platform
spec:
  selector:
    app: streaming-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003

